---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

language: shell
os: linux
git:
  depth: 1
dist: bionic
before_install:
  - eval "$(gimme stable)"
  - sudo apt update
  - sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --no-install-recommends curl
install:
  - curl -fsSL http://bit.ly/install_pkg | PKG="docker make" bash
script:
  - ./install.sh
  - kubectl get all -A -o wide
  - ./deploy.sh
  - ./check.sh
env:
  - DEPLOYMENT_TYPE=k8s
  - DEPLOYMENT_TYPE=k8s PKG_MGR=helm
  - DEPLOYMENT_TYPE=k8s MULTI_CNI=danm
  - DEPLOYMENT_TYPE=k8s MULTI_CNI=danm PKG_MGR=helm
  - DEPLOYMENT_TYPE=k8s MULTI_CNI=nsm
  - DEPLOYMENT_TYPE=k8s MULTI_CNI=nsm PKG_MGR=helm
jobs:
  include:
    - name: Lint validation
      before_install:
        - sudo apt update
        - sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --no-install-recommends curl
      install:
        - curl -fsSL http://bit.ly/install_pkg | PKG="helm tox" bash
      script:
        - tox
        - bash -c 'shopt -s globstar; shellcheck **/*.sh'
        - find k8s -name Chart.yaml -exec dirname {} \; | xargs helm lint
      env:
        - TOXENV=lint
    - name: Docker validation on Vagrant box
      before_install:
        - sudo apt update
        - sudo apt-get install -y -qq -o=Dpkg::Use-Pty=0 --no-install-recommends curl qemu
      install:
        - curl -fsSL http://bit.ly/initVagrant | PROVIDER=libvirt bash
      script:
        - sudo -E vagrant up
        - sudo -E vagrant ssh -- bash /vagrant/check.sh
      env:
        - DEPLOYMENT_TYPE=docker
        - ENABLE_SKYDIVE=true
        - ENABLE_PORTAINER=true
