---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: v1
kind: Pod
metadata:
  name: external-client
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      { "name": "lte-euu" }
    ]'
spec:
  restartPolicy: OnFailure
#  initContainers:
#  - name: configure
#    image: busybox
#    securityContext:
#      capabilities:
#        add: ["NET_ADMIN"]
#    command: ["ip", "route", "add", "10.0.1.0/24", "via", "$(enb_euu_ip)"]
#    env:
#    - name: enb_euu_ip
#      value: $ENB_EUU_IP
  containers:
  - image: electrocucaracha/curl:7.67.0-alpine3.11
    name: external-client
    command:
      - "sh"
    args:
      - "/opt/external-client/script/init.sh"
    env:
    - name: http_server_sgi_ip
      value: $HTTP_SERVER_SGI_IP
    volumeMounts:
      - name: init-script
        mountPath: /opt/external-client/script
  volumes:
    - name: init-script
      configMap:
        name: external-client-init-script
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-client-init-script
data:
  init.sh: |
    while true; do
        curl --connect-timeout 5 ${http_server_sgi_ip}
        sleep 30
    done
