---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mme.fullname" . }}
  labels:
    {{- include "mme.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "mme.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: |
          [
            { "name": "{{ .Values.s11.name }}", "interface": "{{ .Values.s11.interface }}" },
            { "name": "{{ .Values.s1c.name }}", "interface": "{{ .Values.s1c.interface }}" }
          ]
      labels:
        network: epc
        {{- include "mme.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: install
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["cp", "/etc/gw-tester/mme.yml", "/work-dir/mme.yml"]
          volumeMounts:
            - name: config
              mountPath: /etc/gw-tester/
            - name: workdir
              mountPath: /work-dir
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "sh"
          args:
            - "/opt/gw-tester/script/init.sh"
          volumeMounts:
            - name: init-script
              mountPath: /opt/gw-tester/script
            - name: workdir
              mountPath: /etc/gw-tester
      volumes:
        - name: init-script
          configMap:
            name: mme-init-script
        - name: workdir
          emptyDir: {}
        - name: config
          configMap:
            name: mme-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mme-init-script
data:
  init.sh: |
    if [ $(curl http://lte-etcd.default.svc.cluster.local:12379/v2/keys/pgw_s5c_ip -s -o /dev/null -w "%{http_code}") == "200" ]; then
        pgw_s5c_ip=$(curl -s http://lte-etcd.default.svc.cluster.local:12379/v2/keys/pgw_s5c_ip | jq  -r ".node.value")
    else
        pgw_s5c_ip=$(curl -s http://lte-etcd.default.svc.cluster.local:12379/v2/keys/pgw_s5c_ip?wait=true | jq  -r ".node.value")
    fi
    sed -i "s|pgw_s5c_ip:.*|pgw_s5c_ip: \"$pgw_s5c_ip\"|g" /etc/gw-tester/mme.yml

    if [ $(curl http://lte-etcd.default.svc.cluster.local:12379/v2/keys/sgw_s11_ip -s -o /dev/null -w "%{http_code}") == "200" ]; then
        sgw_s11_ip=$(curl -s http://lte-etcd.default.svc.cluster.local:12379/v2/keys/sgw_s11_ip | jq  -r ".node.value")
    else
        sgw_s11_ip=$(curl -s http://lte-etcd.default.svc.cluster.local:12379/v2/keys/sgw_s11_ip?wait=true | jq  -r ".node.value")
    fi
    sed -i "s|sgw_s11_ip:.*|sgw_s11_ip: \"$sgw_s11_ip\"|g" /etc/gw-tester/mme.yml

    s11_ip=$(ifconfig {{ .Values.s11.interface }} | awk '/inet addr/{print substr($2,6)}')
    sed -i "s|  s11_ip:.*|  s11_ip: \"${s11_ip}\"|g" /etc/gw-tester/mme.yml

    s1c_ip=$(ifconfig {{ .Values.s1c.interface }} | awk '/inet addr/{print substr($2,6)}')
    curl -s "http://lte-etcd.default.svc.cluster.local:12379/v2/keys/mme_s1c_ip" -XPUT -d value="$s1c_ip" > /dev/null
    sed -i "s|s1c_addr:.*|s1c_addr: \"${s1c_ip}:36412\"|g" /etc/gw-tester/mme.yml

    ip a
    ip route
    cat /etc/gw-tester/mme.yml

    /opt/gw-tester/bin/mme -config /etc/gw-tester/mme.yml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mme-config
data:
  mme.yml: |
    mcc: "001"
    mnc: "01"
    apn: "gw-tester.go-gtp.example"
    local_addresses:
      s1c_addr: "172.21.1.12:36412"
      s11_ip: "172.22.0.12"
    sgw_s11_ip: "172.22.0.13"
    pgw_s5c_ip: "172.25.1.14"
