---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sgw.fullname" . }}
  labels:
    {{- include "sgw.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "sgw.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        danm.k8s.io/interfaces: |
          [
            {"clusterNetwork":"default"},
            {"clusterNetwork":"{{ .Values.s11.name }}"},
            {"clusterNetwork":"{{ .Values.s1u.name }}"},
            {"clusterNetwork":"{{ .Values.s5u.name }}"},
            {"clusterNetwork":"{{ .Values.s5c.name }}"}
          ]
      labels:
        network: epc
        {{- include "sgw.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: install
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["cp", "/etc/gw-tester/sgw.yml", "/work-dir/sgw.yml"]
          volumeMounts:
            - name: config
              mountPath: /etc/gw-tester/
            - name: workdir
              mountPath: /work-dir
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "sh"
          args:
            - "/opt/gw-tester/script/init.sh"
          volumeMounts:
            - name: init-script
              mountPath: /opt/gw-tester/script
            - name: workdir
              mountPath: /etc/gw-tester
      volumes:
        - name: init-script
          configMap:
            name: sgw-init-script
        - name: workdir
          emptyDir: {}
        - name: config
          configMap:
            name: sgw-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sgw-init-script
data:
  init.sh: |
    s5u_ip=$(ifconfig $(ip a | grep {{ .Values.s5u.container_prefix | quote }} | awk -v FS="(: |@)" '{print $2; exit}') | awk '/inet addr/{print substr($2,6)}')
    sed -i "s|s5u_ip:.*|s5u_ip: \"${s5u_ip}\"|g" /etc/gw-tester/sgw.yml

    s5c_ip=$(ifconfig $(ip a | grep {{ .Values.s5c.container_prefix | quote }} | awk -v FS="(: |@)" '{print $2; exit}') | awk '/inet addr/{print substr($2,6)}')
    sed -i "s|s5c_ip:.*|s5c_ip: \"${s5c_ip}\"|g" /etc/gw-tester/sgw.yml

    s11_ip=$(ifconfig $(ip a | grep {{ .Values.s11.container_prefix | quote }} | awk -v FS="(: |@)" '{print $2; exit}') | awk '/inet addr/{print substr($2,6)}')
    curl -s http://lte-etcd.default.svc.cluster.local:12379/v2/keys/sgw_s11_ip -XPUT -d value="$s11_ip" > /dev/null
    sed -i "s|s11_ip:.*|s11_ip: \"${s11_ip}\"|g" /etc/gw-tester/sgw.yml

    s1u_ip=$(ifconfig $(ip a | grep {{ .Values.s1u.container_prefix | quote }} | awk -v FS="(: |@)" '{print $2; exit}') | awk '/inet addr/{print substr($2,6)}')
    sed -i "s|s1u_ip:.*|s1u_ip: \"${s1u_ip}\"|g" /etc/gw-tester/sgw.yml

    ip a
    ip route
    cat /etc/gw-tester/sgw.yml

    /opt/gw-tester/bin/sgw -config /etc/gw-tester/sgw.yml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sgw-config
data:
  sgw.yml: |
    local_addresses:
      s11_ip: "172.22.0.13"
      s1u_ip: "172.21.0.13"
      s5c_ip: "172.25.1.13"
      s5u_ip: "172.25.0.13"
